package fr.formation.inti;
// Generated 6 f�vr. 2023 � 12:03:42 by Hibernate Tools 5.1.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "groupe", catalog = "bd_music_project", uniqueConstraints = @UniqueConstraint(columnNames = "Groupe_Email"))
public class Groupe implements java.io.Serializable {

	private Integer groupeId;
	private Users users;
	private String groupeName;
	private String groupeEmail;
	private Integer groupeMembersNmb;
	private Byte groupeIsRecruting;
	private Set<GroupeMembers> groupeMemberses = new HashSet<GroupeMembers>(0);
	private Set<GroupeEvenement> groupeEvenements = new HashSet<GroupeEvenement>(0);
	private Set<Evenement> evenements = new HashSet<Evenement>(0);
	private Set<GenreGroupe> genreGroupes = new HashSet<GenreGroupe>(0);

	public Groupe() {
	}

	public Groupe(String groupeName, String groupeEmail) {
		this.groupeName = groupeName;
		this.groupeEmail = groupeEmail;
	}

	public Groupe(Users users, String groupeName, String groupeEmail, Integer groupeMembersNmb, Byte groupeIsRecruting,
			Set<GroupeMembers> groupeMemberses, Set<GroupeEvenement> groupeEvenements, Set<Evenement> evenements,
			Set<GenreGroupe> genreGroupes) {
		this.users = users;
		this.groupeName = groupeName;
		this.groupeEmail = groupeEmail;
		this.groupeMembersNmb = groupeMembersNmb;
		this.groupeIsRecruting = groupeIsRecruting;
		this.groupeMemberses = groupeMemberses;
		this.groupeEvenements = groupeEvenements;
		this.evenements = evenements;
		this.genreGroupes = genreGroupes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Groupe_id", unique = true, nullable = false)
	public Integer getGroupeId() {
		return this.groupeId;
	}

	public void setGroupeId(Integer groupeId) {
		this.groupeId = groupeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Creator_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Groupe_name", nullable = false, length = 500)
	public String getGroupeName() {
		return this.groupeName;
	}

	public void setGroupeName(String groupeName) {
		this.groupeName = groupeName;
	}

	@Column(name = "Groupe_Email", unique = true, nullable = false, length = 500)
	public String getGroupeEmail() {
		return this.groupeEmail;
	}

	public void setGroupeEmail(String groupeEmail) {
		this.groupeEmail = groupeEmail;
	}

	@Column(name = "Groupe_members_nmb")
	public Integer getGroupeMembersNmb() {
		return this.groupeMembersNmb;
	}

	public void setGroupeMembersNmb(Integer groupeMembersNmb) {
		this.groupeMembersNmb = groupeMembersNmb;
	}

	@Column(name = "Groupe_isRecruting")
	public Byte getGroupeIsRecruting() {
		return this.groupeIsRecruting;
	}

	public void setGroupeIsRecruting(Byte groupeIsRecruting) {
		this.groupeIsRecruting = groupeIsRecruting;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<GroupeMembers> getGroupeMemberses() {
		return this.groupeMemberses;
	}

	public void setGroupeMemberses(Set<GroupeMembers> groupeMemberses) {
		this.groupeMemberses = groupeMemberses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<GroupeEvenement> getGroupeEvenements() {
		return this.groupeEvenements;
	}

	public void setGroupeEvenements(Set<GroupeEvenement> groupeEvenements) {
		this.groupeEvenements = groupeEvenements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<Evenement> getEvenements() {
		return this.evenements;
	}

	public void setEvenements(Set<Evenement> evenements) {
		this.evenements = evenements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<GenreGroupe> getGenreGroupes() {
		return this.genreGroupes;
	}

	public void setGenreGroupes(Set<GenreGroupe> genreGroupes) {
		this.genreGroupes = genreGroupes;
	}

}
