package fr.formation.inti;
// Generated 6 f�vr. 2023 � 12:03:42 by Hibernate Tools 5.1.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersEvenement generated by hbm2java
 */
@Entity
@Table(name = "users_evenement", catalog = "bd_music_project")
public class UsersEvenement implements java.io.Serializable {

	private UsersEvenementId id;
	private Evenement evenement;
	private Users users;

	public UsersEvenement() {
	}

	public UsersEvenement(UsersEvenementId id, Evenement evenement, Users users) {
		this.id = id;
		this.evenement = evenement;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "usersId", column = @Column(name = "Users_id", nullable = false)),
			@AttributeOverride(name = "evenementId", column = @Column(name = "Evenement_id", nullable = false)) })
	public UsersEvenementId getId() {
		return this.id;
	}

	public void setId(UsersEvenementId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Evenement_id", nullable = false, insertable = false, updatable = false)
	public Evenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(Evenement evenement) {
		this.evenement = evenement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
