package fr.formation.inti.entity;
// Generated 7 f�vr. 2023 � 14:53:51 by Hibernate Tools 5.1.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactId generated by hbm2java
 */
@Embeddable
public class ContactId implements java.io.Serializable {

	private int usersId;
	private int contactId;

	public ContactId() {
	}

	public ContactId(int usersId, int contactId) {
		this.usersId = usersId;
		this.contactId = contactId;
	}

	@Column(name = "Users_id", nullable = false)
	public int getUsersId() {
		return this.usersId;
	}

	public void setUsersId(int usersId) {
		this.usersId = usersId;
	}

	@Column(name = "contact_id", nullable = false)
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactId))
			return false;
		ContactId castOther = (ContactId) other;

		return (this.getUsersId() == castOther.getUsersId()) && (this.getContactId() == castOther.getContactId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsersId();
		result = 37 * result + this.getContactId();
		return result;
	}

}
