package fr.formation.inti.entity;
// Generated 7 f vr. 2023   14:05:16 by Hibernate Tools 5.1.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "bd_music_project")
public class Contact implements java.io.Serializable {

	private Integer id;
	private Users usersByUsersId;
	private Users usersByContactId;

	public Contact() {
	}

//	public Contact(Integer id, Users usersByUsersId, Users usersByContactId) {
//		this.id = id;
//		this.usersByUsersId = usersByUsersId;
//		this.usersByContactId = usersByContactId;
//	}
	
	public Contact( Users usersByUsersId, Users usersByContactId) {
	
		this.usersByUsersId = usersByUsersId;
		this.usersByContactId = usersByContactId;
	}

	

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_amitié")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "Users_id")
	public Users getUsersByUsersId() {
		return this.usersByUsersId;
	}

	public void setUsersByUsersId(Users usersByUsersId) {
		this.usersByUsersId = usersByUsersId;
	}

	@ManyToOne
	@JoinColumn(name = "contact_id")
	public Users getUsersByContactId() {
		return this.usersByContactId;
	}

	public void setUsersByContactId(Users usersByContactId) {
		this.usersByContactId = usersByContactId;
	}

}
