package fr.formation.inti.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupeEvenementId generated by hbm2java
 */
@Embeddable

public class GroupeEvenementId implements java.io.Serializable{
	
	private int groupeId;
	private int evenementId;

	public GroupeEvenementId() {
	}

	public GroupeEvenementId(int groupeId, int evenementId) {
		this.groupeId = groupeId;
		this.evenementId = evenementId;
	}

	@Column(name = "Groupe_id", nullable = false)
	public int getGroupeId() {
		return this.groupeId;
	}

	public void setGroupeId(int groupeId) {
		this.groupeId = groupeId;
	}

	@Column(name = "Evenement_id", nullable = false)
	public int getEvenementId() {
		return this.evenementId;
	}

	public void setEvenementId(int evenementId) {
		this.evenementId = evenementId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupeEvenementId))
			return false;
		GroupeEvenementId castOther = (GroupeEvenementId) other;

		return (this.getGroupeId() == castOther.getGroupeId()) && (this.getEvenementId() == castOther.getEvenementId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupeId();
		result = 37 * result + this.getEvenementId();
		return result;
	}


}
