package fr.formation.inti.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersInstrumentsId generated by hbm2java
 */
@Embeddable
public class UsersInstrumentsId implements java.io.Serializable {

	private int usersId;
	private int instrId;

	public UsersInstrumentsId() {
	}

	public UsersInstrumentsId(int usersId, int instrId) {
		this.usersId = usersId;
		this.instrId = instrId;
	}

	@Column(name = "Users_id", nullable = false)
	public int getUsersId() {
		return this.usersId;
	}

	public void setUsersId(int usersId) {
		this.usersId = usersId;
	}

	@Column(name = "Instr_id", nullable = false)
	public int getInstrId() {
		return this.instrId;
	}

	public void setInstrId(int instrId) {
		this.instrId = instrId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersInstrumentsId))
			return false;
		UsersInstrumentsId castOther = (UsersInstrumentsId) other;

		return (this.getUsersId() == castOther.getUsersId()) && (this.getInstrId() == castOther.getInstrId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsersId();
		result = 37 * result + this.getInstrId();
		return result;
	}
}
