package fr.formation.inti.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersGenre generated by hbm2java
 */
@Entity
@Table(name = "users_genre", catalog = "bd_music_project")
public class UsersGenre implements java.io.Serializable{
	
	private UsersGenreId id;
	private GenreMusic genreMusic;
	private Users users;

	public UsersGenre() {
	}

	public UsersGenre(UsersGenreId id, GenreMusic genreMusic, Users users) {
		this.id = id;
		this.genreMusic = genreMusic;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "usersId", column = @Column(name = "Users_id", nullable = false)),
			@AttributeOverride(name = "genreId", column = @Column(name = "Genre_id", nullable = false)) })
	public UsersGenreId getId() {
		return this.id;
	}

	public void setId(UsersGenreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Genre_id", nullable = false, insertable = false, updatable=false )
	public GenreMusic getGenreMusic() {
		return this.genreMusic;
	}

	public void setGenreMusic(GenreMusic genreMusic) {
		this.genreMusic = genreMusic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", nullable = false, insertable = false, updatable=false )
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
