package fr.formation.inti.entity;
// Generated 7 f�vr. 2023 � 16:30:26 by Hibernate Tools 5.1.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name = "users_roles", catalog = "bd_music_project")
public class UsersRoles implements java.io.Serializable {

	private Integer rolesid;
	private Users users;
	private String usersEmail;
	private String usersRole;

	public UsersRoles() {
	}

	public UsersRoles(Users users, String usersEmail, String usersRole) {
		this.users = users;
		this.usersEmail = usersEmail;
		this.usersRole = usersRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Rolesid", unique = true, nullable = false)
	public Integer getRolesid() {
		return this.rolesid;
	}

	public void setRolesid(Integer rolesid) {
		this.rolesid = rolesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usersid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Users_email")
	public String getUsersEmail() {
		return this.usersEmail;
	}

	public void setUsersEmail(String usersEmail) {
		this.usersEmail = usersEmail;
	}

	@Column(name = "USERS_ROLE")
	public String getUsersRole() {
		return this.usersRole;
	}

	public void setUsersRole(String usersRole) {
		this.usersRole = usersRole;
	}

}
