package fr.formation.inti.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AudioUser generated by hbm2java
 */
@Entity
@Table(name = "audio_user", catalog = "bd_music_project")
public class AudioUser implements java.io.Serializable{
	
	private int audioId;
	private Users users;
	private String audioName;

	public AudioUser() {
	}

	public AudioUser(int audioId, Users users) {
		this.audioId = audioId;
		this.users = users;
	}

	public AudioUser(int audioId, Users users, String audioName) {
		this.audioId = audioId;
		this.users = users;
		this.audioName = audioName;
	}

	@Id

	@Column(name = "Audio_id", unique = true, nullable = false)
	public int getAudioId() {
		return this.audioId;
	}

	public void setAudioId(int audioId) {
		this.audioId = audioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", updatable = false,nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Audio_name", length = 200)
	public String getAudioName() {
		return this.audioName;
	}

	public void setAudioName(String audioName) {
		this.audioName = audioName;
	}
	
	@Transient
	public String getAudioPath() {
		if (audioName == null ||  users == null)
			return null;

		return "/users-audio/" +  users + "/" + audioName;
	}

}
