package fr.formation.inti.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AudioGroupe generated by hbm2java
 */
@Entity
@Table(name = "audio_groupe", catalog = "bd_music_project")
public class AudioGroupe implements java.io.Serializable {
	
	private int audioId;
	private Groupe groupe;
	private String audioName;

	public AudioGroupe() {
	}

	public AudioGroupe(int audioId, Groupe groupe) {
		this.audioId = audioId;
		this.groupe = groupe;
	}

	public AudioGroupe(int audioId, Groupe groupe, String audioName) {
		this.audioId = audioId;
		this.groupe = groupe;
		this.audioName = audioName;
	}

	@Id

	@Column(name = "Audio_id", unique = true, nullable = false)
	public int getAudioId() {
		return this.audioId;
	}

	public void setAudioId(int audioId) {
		this.audioId = audioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Groupe_id", nullable = false)
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@Column(name = "Audio_name", length = 200)
	public String getAudioName() {
		return this.audioName;
	}

	public void setAudioName(String audioName) {
		this.audioName = audioName;
	}
	
	@Transient
	public String getAudioPath() {
		if (audioName == null ||  groupe == null)
			return null;

		return "/groupe-audio/" +  groupe + "/" + audioName;
	}


}
