package fr.formation.inti.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupeEvenement generated by hbm2java
 */
@Entity
@Table(name = "groupe_evenement", catalog = "bd_music_project")

public class GroupeEvenement implements java.io.Serializable {

	private GroupeEvenementId id;
	private Evenement evenement;
	private Groupe groupe;

	public GroupeEvenement() {
	}

	public GroupeEvenement(GroupeEvenementId id, Evenement evenement, Groupe groupe) {
		this.id = id;
		this.evenement = evenement;
		this.groupe = groupe;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "groupeId", column = @Column(name = "Groupe_id", nullable = false)),
			@AttributeOverride(name = "evenementId", column = @Column(name = "Evenement_id", nullable = false)) })
	public GroupeEvenementId getId() {
		return this.id;
	}

	public void setId(GroupeEvenementId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(nullable = false, insertable = false, updatable = false)
	public Evenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(Evenement evenement) {
		this.evenement = evenement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(nullable = false, insertable = false,updatable = false)
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}
}
