package fr.formation.inti.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersEvenement generated by hbm2java
 */
@Entity
@Table(name = "users_evenement", catalog = "bd_music_project")

public class UsersEvenement implements java.io.Serializable{
	
	private Integer id;
	private Evenement evenement;
	private Users users;

	public UsersEvenement() {
	}

	public UsersEvenement(Evenement evenement, Users users) {
		super();
		this.evenement = evenement;
		this.users = users;
	}


	public UsersEvenement(Integer id, Evenement evenement, Users users) {
		this.id = id;
		this.evenement = evenement;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Evenement_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Evenement_id", nullable = false, insertable = false, updatable = false)
	public Evenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(Evenement evenement) {
		this.evenement = evenement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}