package fr.formation.inti.entity;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Evenement generated by hbm2java
 */
@Entity
@Table(name = "evenement", catalog = "bd_music_project")
public class Evenement implements java.io.Serializable {
	private Integer evenementId;
	private GenreMusic genreMusic;
	private Groupe groupe;
	private Users users;
	private String evenementName;
	private String evenementBio;
	private String evenementAdress;
	private String evenementZip;
	private String evenementCity;
	private LocalDateTime evenementDatedebut;
	private LocalDateTime evenementDatefin;
	private String evenementType;
	private String evenementLieu;

	private Set<UsersEvenement> usersEvenements = new HashSet<UsersEvenement>(0);
	private Set<GroupeEvenement> groupeEvenements = new HashSet<GroupeEvenement>(0);

	public Evenement() {
	}

	public Evenement(Integer evenementId, GenreMusic genreMusic, Groupe groupe, Users users, String evenementName,
			String evenementBio, String evenementAdress, String evenementZip, String evenementCity,
			LocalDateTime evenementDatedebut, LocalDateTime evenementDatefin, String evenementType,
			String evenementLieu, Set<UsersEvenement> usersEvenements, Set<GroupeEvenement> groupeEvenements) {
		super();
		this.evenementId = evenementId;
		this.genreMusic = genreMusic;
		this.groupe = groupe;
		this.users = users;
		this.evenementName = evenementName;
		this.evenementBio = evenementBio;
		this.evenementAdress = evenementAdress;
		this.evenementZip = evenementZip;
		this.evenementCity = evenementCity;
		this.evenementDatedebut = evenementDatedebut;
		this.evenementDatefin = evenementDatefin;
		this.evenementType = evenementType;
		this.evenementLieu = evenementLieu;
		this.usersEvenements = usersEvenements;
		this.groupeEvenements = groupeEvenements;
	}

	public Evenement(GenreMusic genreMusic, Groupe groupe, Users users, String evenementName, String evenementBio,
			String evenementAdress, String evenementZip, String evenementCity, LocalDateTime evenementDatedebut,
			LocalDateTime evenementDatefin, String evenementType, String evenementLieu,
			Set<UsersEvenement> usersEvenements, Set<GroupeEvenement> groupeEvenements) {
		super();
		this.genreMusic = genreMusic;
		this.groupe = groupe;
		this.users = users;
		this.evenementName = evenementName;
		this.evenementBio = evenementBio;
		this.evenementAdress = evenementAdress;
		this.evenementZip = evenementZip;
		this.evenementCity = evenementCity;
		this.evenementDatedebut = evenementDatedebut;
		this.evenementDatefin = evenementDatefin;
		this.evenementType = evenementType;
		this.evenementLieu = evenementLieu;
		this.usersEvenements = usersEvenements;
		this.groupeEvenements = groupeEvenements;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Evenement_id", unique = true, nullable = false)
	public Integer getEvenementId() {
		return this.evenementId;
	}

	@Column(name = "Evenement_lieu", nullable = false, length = 500)
	public String getEvenementLieu() {
		return evenementLieu;
	}

	public void setEvenementLieu(String evenementLieu) {
		this.evenementLieu = evenementLieu;
	}

	public void setEvenementId(Integer evenementId) {
		this.evenementId = evenementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Evenement_genre", nullable = false)
	public GenreMusic getGenreMusic() {
		return this.genreMusic;
	}

	public void setGenreMusic(GenreMusic genreMusic) {
		this.genreMusic = genreMusic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Groupe_crea")
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_crea", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Evenement_name", nullable = false, length = 500)
	public String getEvenementName() {
		return this.evenementName;
	}

	public void setEvenementName(String evenementName) {
		this.evenementName = evenementName;
	}

	@Column(name = "Evenement_bio", length = 2000)
	public String getEvenementBio() {
		return this.evenementBio;
	}

	public void setEvenementBio(String evenementBio) {
		this.evenementBio = evenementBio;
	}

	@Column(name = "Evenement_Adress", nullable = false, length = 1000)
	public String getEvenementAdress() {
		return this.evenementAdress;
	}

	public void setEvenementAdress(String evenementAdress) {
		this.evenementAdress = evenementAdress;
	}

	@Column(name = "Evenement_Zip", nullable = false, length = 50)
	public String getEvenementZip() {
		return this.evenementZip;
	}

	public void setEvenementZip(String evenementZip) {
		this.evenementZip = evenementZip;
	}

	@Column(name = "Evenement_City", nullable = false, length = 200)
	public String getEvenementCity() {
		return this.evenementCity;
	}

	public void setEvenementCity(String evenementCity) {
		this.evenementCity = evenementCity;
	}

	@Column(name = "Evenement_datedebut", nullable = false, length = 19)
	public LocalDateTime getEvenementDatedebut() {
		return evenementDatedebut;
	}

	public void setEvenementDatedebut(LocalDateTime evenementDatedebut) {
		this.evenementDatedebut = evenementDatedebut;
	}

	@Column(name = "Evenement_datefin", nullable = false, length = 19)
	public LocalDateTime getEvenementDatefin() {
		return evenementDatefin;
	}

	public void setEvenementDatefin(LocalDateTime evenementDatefin) {
		this.evenementDatefin = evenementDatefin;
	}

	@Column(name = "Evenement_type")
	public String getEvenementType() {
		return evenementType;
	}

	public void setEvenementType(String evenementType) {
		this.evenementType = evenementType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evenement")
	public Set<UsersEvenement> getUsersEvenements() {
		return this.usersEvenements;
	}

	public void setUsersEvenements(Set<UsersEvenement> usersEvenements) {
		this.usersEvenements = usersEvenements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evenement")
	public Set<GroupeEvenement> getGroupeEvenements() {
		return this.groupeEvenements;
	}

	public void setGroupeEvenements(Set<GroupeEvenement> groupeEvenements) {
		this.groupeEvenements = groupeEvenements;
	}

	@Override
	public String toString() {
		return "Evenement [evenementId=" + evenementId + ", genreMusic=" + genreMusic + ", evenementName="
				+ evenementName + ", evenementBio=" + evenementBio + ", evenementAdress=" + evenementAdress
				+ ", evenementZip=" + evenementZip + ", evenementCity=" + evenementCity + ", evenementDatedebut="
				+ evenementDatedebut + ", evenementDatefin=" + evenementDatefin + ", evenementType=" + evenementType
				+ ", evenementLieu=" + evenementLieu + "]";
	}
}
