package fr.formation.inti.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GenreGroupe generated by hbm2java
 */
@Entity
@Table(name = "genre_groupe", catalog = "bd_music_project")

public class GenreGroupe implements java.io.Serializable{
	
	private Integer id;
	private GenreMusic genreMusic;
	private Groupe groupe;

	public GenreGroupe() {
	}


	public GenreGroupe(GenreMusic genreMusic, Groupe groupe) {
		super();
		this.genreMusic = genreMusic;
		this.groupe = groupe;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Genre_groupekey")
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Genre_id", nullable = false)
	public GenreMusic getGenreMusic() {
		return this.genreMusic;
	}

	public void setGenreMusic(GenreMusic genreMusic) {
		this.genreMusic = genreMusic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Groupe_id", nullable = false)
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}


	@Override
	public String toString() {
		return "GenreGroupe [id=" + id + ", genreMusic=" + genreMusic + ", groupe=" + groupe + "]";
	}
	
	

}
