package fr.formation.inti.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupeMembers generated by hbm2java
 */
@Entity
@Table(name = "groupe_members", catalog = "bd_music_project")
public class GroupeMembers implements java.io.Serializable{

	
	private Integer gmembersid;
//	private GroupeMembersId id;
	private Groupe groupe;
	private Users users;

	public GroupeMembers() {
	}




	
//
//	@AttributeOverrides({ @AttributeOverride(name = "groupeId", column = @Column(name = "Groupe_id", nullable = false)),
//			@AttributeOverride(name = "usersMembers", column = @Column(name = "Users_members", nullable = false)) })
//	public GroupeMembersId getId() {
//		return this.id;
//	}
//
//	public void setId(GroupeMembersId id) {
//		this.id = id;
//	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Groupe_memberskey", unique = true, nullable = false)
	public Integer getGmembersid() {
		return gmembersid;
	}

	public void setGmembersid(Integer gmembersid) {
		this.gmembersid = gmembersid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Groupe_id")
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_members")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public GroupeMembers(Groupe groupe, Users users) {
		super();
		this.groupe = groupe;
		this.users = users;
	}
	
}