package fr.formation.inti.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Postulations generated by hbm2java
 */
@Entity
@Table(name = "postulations", catalog = "bd_music_project")
public class Postulations implements java.io.Serializable {

	private Integer postulationsId;
	private Groupe groupe;
	private Users users;
	private String statut;

	public Postulations() {
	}

	public Postulations(Groupe groupe, Users users, String statut) {
		this.groupe = groupe;
		this.users = users;
		this.statut = statut;
	}
	
	public Postulations(Users user, Groupe groupe) {
		super();
		this.users = user;
		this.groupe = groupe;
		this.statut = "en attente";
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "postulations_id", unique = true, nullable = false)
	public Integer getPostulationsId() {
		return this.postulationsId;
	}

	public void setPostulationsId(Integer postulationsId) {
		this.postulationsId = postulationsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupe_id", nullable = false)
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "postulant_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "statut", nullable = false, length = 45)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

}