package fr.formation.inti.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersGenre generated by hbm2java
 */
@Entity
@Table(name = "users_genre", catalog = "bd_music_project")
public class UsersGenre implements java.io.Serializable{
	
	private Integer id;
	private GenreMusic genreMusic;
	private Users users;

	public UsersGenre() {
	}

	public UsersGenre( GenreMusic genreMusic, Users users) {

		this.genreMusic = genreMusic;
		this.users = users;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Users_genrekey", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Genre_id", nullable = false )
	public GenreMusic getGenreMusic() {
		return this.genreMusic;
	}

	public void setGenreMusic(GenreMusic genreMusic) {
		this.genreMusic = genreMusic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
