package fr.formation.inti.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersInstrumentsId generated by hbm2java
 */
@Embeddable
public class UsersInstrumentsId implements java.io.Serializable {

	private Integer usersId;
	private Integer instrId;

	public UsersInstrumentsId() {
	}

	public UsersInstrumentsId(Integer usersId, Integer instrId) {
		this.usersId = usersId;
		this.instrId = instrId;
	}

	@Column(name = "Users_id", nullable = false)
	public Integer getUsersId() {
		return this.usersId;
	}

	public void setUsersId(Integer usersId) {
		this.usersId = usersId;
	}

	@Column(name = "Instr_id", nullable = false)
	public Integer getInstrId() {
		return this.instrId;
	}

	public void setInstrId(Integer instrId) {
		this.instrId = instrId;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsersId();
		result = 37 * result + this.getInstrId();
		return result;
	}
}
